name: Update Schema JSON
on:
  schedule:
    - cron:  '0 21 * * *'
  workflow_dispatch:
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Fetch release version
        id: google-tf
        run: |
          latest_tag=$(curl -sL https://api.github.com/repos/hashicorp/terraform-provider-google/releases/latest | jq -r ".tag_name")
          echo "latest_tag=$latest_tag" >> $GITHUB_OUTPUT
          echo $latest_tag > google-tf.version
      - name: Terraform Schema GA Generate 
        id: gen-ga
        run: | 
          cd ga
          terraform init -upgrade
          terraform providers schema -json > ../ga-schema.json
      - name: Terraform Schema Beta Generate 
        id: gen-beta
        run: | 
          cd beta
          terraform init -upgrade
          terraform providers schema -json > ../beta-schema.json
      - name: Check for modified files
        id: git-check
        run: echo "modified=$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")" >> $GITHUB_OUTPUT
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'drandell'
          git config --global user.email 'drandell@users.noreply.github.com'
          git commit -am "New release version ${{ steps.google-tf.outputs.latest_tag }}"
          git push
